---
  dependency:
    name: galaxy
  driver:
    name: docker
  platforms:
    - &instance
      name: instance-r
      image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
      command: ${MOLECULE_DOCKER_COMMAND:-""}
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      capabilities:
        - SYS_ADMIN
      pre_build_image: true
      platform: linux/amd64
    - <<: *instance
      name: instance-r-rh
      image: "registry.access.redhat.com/${MOLECULE_DISTRO:-ubi9}/ubi-init"
      command: "/usr/sbin/init"
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:rw
      privileged: true
      cgroupns_mode: host
  provisioner:
    name: ansible
    playbooks:
      prepare: prepare.yml
      converge: converge.yml
      verify: verify.yml