---
- name: Verify
  hosts: all
  pre_tasks:
    - name: include vars
      include_vars: "{{ playbook_dir }}/../../tests/vars/main.yml"
  tasks:
    - name: include tasks
      include_tasks: "{{ playbook_dir }}/../../tests/tasks/post.yml"
