---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '30 1 * * 3'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install test dependencies
        run: pip install ansible-lint[community,yamllint]

      - name: Lint code
        run: |
          yamllint .
          ansible-lint

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "${{ github.repository }}"
    needs:
      - lint
    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: ubuntu2004
          - distro: ubi8
            platform: instance-r-rh
          - distro: ubi9
            platform: instance-r-rh

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"

      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install test dependencies
        run: pip install -r requirements.txt

      - name: Run Molecule tests
        run: |
          molecule test --platform-name ${MOLECULE_PLATFORM:-instance-r}
        env:
          ANSIBLE_FORCE_COLOR: '1'
          ANSIBLE_VERBOSITY: '2'
          MOLECULE_DEBUG: '1'
          MOLECULE_DISTRO: "${{ matrix.distro }}"
          MOLECULE_PLATFORM: "${{ matrix.platform }}"
          PY_COLORS: '1'
